services:
  postgres:
    image: debezium/postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=userdb
    networks:
      - server-db-networks
    volumes:
      - /use-case-debezium/debezium-case/data/postgres:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=bruno.hensilva@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2019!
    depends_on:
      - postgres
    networks:
      - server-db-networks

networks:
  server-db-networks:
    driver: bridge